import type {
  Asset,
  AssetStatus,
  InventoryPart,
  Supplier,
  WorkOrder,
  WorkOrderSeverity,
  WorkOrderStatus,
} from '../types';
import type { LiveAssetDto, LivePartDto, LiveSupplierDto, LiveWorkOrderDto } from './liveApi';

const toAssetStatus = (status: string): AssetStatus => {
  const normalized = status.toLowerCase();
  if (normalized === 'fault' || normalized === 'down') return 'DOWN';
  if (normalized === 'warning' || normalized === 'degraded') return 'DEGRADED';
  return 'HEALTHY';
};

export const mapLiveAsset = (dto: LiveAssetDto): Asset => {
  const telemetrySensors = [
    {
      id: 'temperature',
      name: 'Temperature',
      type: 'Temperature',
      value: dto.temperature,
      unit: '°C',
    },
    { id: 'vibration', name: 'Vibration', type: 'Vibration', value: dto.vibration, unit: 'mm/s' },
    { id: 'load', name: 'Load', type: 'Load', value: dto.load, unit: '%' },
    { id: 'power', name: 'Power', type: 'Power', value: dto.power, unit: 'kW' },
  ];

  return {
    id: dto.id,
    name: dto.name,
    assetType: dto.type,
    location: dto.location,
    healthScore: dto.health,
    status: toAssetStatus(dto.status),
    machineClass: dto.model,
    lastSeenAt: dto.lastSeenAt,
    telemetrySource: dto.telemetrySource,
    sensors:
      dto.sensors
        ?.filter((sensor) => Number.isFinite(sensor.currentValue))
        .map((sensor) => ({
          ...sensor,
          rawValue: sensor.currentValue,
          lastSeenAt: dto.lastSeenAt,
        })) ??
      telemetrySensors
        .filter((sensor) => Number.isFinite(sensor.value))
        .map((sensor) => ({
          id: `${dto.id}-${sensor.id}`,
          name: sensor.name,
          type: sensor.type,
          currentValue: sensor.value,
          unit: sensor.unit,
          history: [sensor.value], // Start the display trend with the validated session snapshot.
        })),
  };
};

const toWorkOrderStatus = (status: string): WorkOrderStatus => {
  const normalized = status.toUpperCase().replace(/[ -]/g, '_');
  if (normalized === 'RESOLVED' || normalized === 'COMPLETED') return 'RESOLVED';
  if (normalized === 'IN_PROGRESS') return 'IN_PROGRESS';
  if (normalized === 'SCHEDULED') return 'SCHEDULED';
  if (normalized === 'AUTO_GENERATED') return 'AUTO_GENERATED';
  return 'ASSIGNED';
};

const toSeverity = (priority: string): WorkOrderSeverity => {
  const normalized = priority.toUpperCase();
  if (normalized === 'CRITICAL' || normalized === 'HIGH' || normalized === 'MEDIUM')
    return normalized;
  return 'LOW';
};

const readingMap = (value: unknown): Record<string, number> => {
  try {
    const readings = typeof value === 'string' ? JSON.parse(value) : value;
    if (!readings || typeof readings !== 'object' || Array.isArray(readings)) return {};
    return Object.fromEntries(
      Object.entries(readings).filter(
        (entry): entry is [string, number] =>
          typeof entry[1] === 'number' && Number.isFinite(entry[1]),
      ),
    );
  } catch {
    return {};
  }
};

export const mapLiveWorkOrder = (dto: LiveWorkOrderDto, assets: Asset[]): WorkOrder => ({
  id: dto.id,
  assetId: dto.asset,
  assetName: assets.find((asset) => asset.id === dto.asset)?.name ?? dto.asset,
  severity: toSeverity(dto.priority),
  status: toWorkOrderStatus(dto.status),
  title: dto.title,
  assignedTechnician: dto.owner,
  description: dto.description,
  createdAt: dto.createdAt,
  resolvedAt: dto.resolvedAt,
  aiRootCause: dto.recommendedAction,
  triggerReadings: readingMap(dto.triggerReadings),
  incidentId:
    dto.incidentId === undefined || dto.incidentId === null ? undefined : String(dto.incidentId),
  autoGenerated: dto.source.toLowerCase().includes('automatic'),
});

export const mapLivePart = (dto: LivePartDto, suppliers: Supplier[]): InventoryPart => ({
  id: dto.id,
  name: dto.name,
  quantityOnHand: dto.onHand,
  reorderLevel: dto.reorderLevel,
  unitCost: dto.unitCost,
  supplierId: dto.supplierId,
  sku: dto.sku,
  category: dto.category,
  compatibleAssets:
    typeof dto.compatibleAssets === 'string'
      ? JSON.parse(dto.compatibleAssets)
      : dto.compatibleAssets,
  supplierName:
    suppliers.find((supplier) => supplier.id === dto.supplierId)?.name ?? dto.supplierId,
});

export const mapLiveSupplier = (dto: LiveSupplierDto): Supplier => ({
  id: dto.id,
  name: dto.name,
  contact: dto.contact,
  contactPhone: dto.phone,
  rating: dto.rating,
});

export const mapLiveAssets = (assets: LiveAssetDto[]) =>
  assets
    .filter(
      (dto) =>
        typeof dto.id === 'string' &&
        typeof dto.status === 'string' &&
        Number.isFinite(dto.health) &&
        dto.health >= 0 &&
        dto.health <= 100 &&
        dto.load >= 0 &&
        dto.load <= 100 &&
        dto.temperature >= -50 &&
        dto.temperature <= 500 &&
        dto.vibration >= 0 &&
        dto.power >= 0,
    )
    .map(mapLiveAsset);
export const mapLiveSuppliers = (suppliers: LiveSupplierDto[]) => suppliers.map(mapLiveSupplier);
export const mapLiveParts = (parts: LivePartDto[], suppliers: Supplier[]) =>
  parts.map((part) => mapLivePart(part, suppliers));
export const mapLiveWorkOrders = (orders: LiveWorkOrderDto[], assets: Asset[]) =>
  orders.map((order) => mapLiveWorkOrder(order, assets));
