import type { Asset, AssetStatus, InventoryPart, Supplier, WorkOrder, WorkOrderSeverity, WorkOrderStatus } from '../types';
import type { LiveAssetDto, LivePartDto, LiveSupplierDto, LiveWorkOrderDto } from './liveApi';

const toAssetStatus = (status: string): AssetStatus => {
  const normalized = status.toLowerCase();
  if (normalized === 'fault' || normalized === 'down') return 'DOWN';
  if (normalized === 'warning' || normalized === 'degraded') return 'DEGRADED';
  return 'HEALTHY';
};

export const mapLiveAsset = (dto: LiveAssetDto): Asset => {
  const telemetrySensors = [
    { id: 'temperature', name: 'Temperature', type: 'Temperature', value: dto.temperature, unit: '°C' },
    { id: 'vibration', name: 'Vibration', type: 'Vibration', value: dto.vibration, unit: 'mm/s' },
    { id: 'load', name: 'Load', type: 'Load', value: dto.load, unit: '%' },
    { id: 'power', name: 'Power', type: 'Power', value: dto.power, unit: 'kW' }
  ];

  return {
    id: dto.id,
    name: dto.name,
    assetType: dto.type,
    location: dto.location,
    healthScore: dto.health,
    status: toAssetStatus(dto.status),
    machineClass: dto.model,
    sensors: telemetrySensors.map((sensor) => ({
      id: `${dto.id}-${sensor.id}`,
      name: sensor.name,
      type: sensor.type,
      currentValue: sensor.value,
      unit: sensor.unit,
      history: sensor.id === 'temperature' && dto.trend.length ? dto.trend : [sensor.value]
    }))
  };
};

const toWorkOrderStatus = (status: string): WorkOrderStatus => {
  const normalized = status.toUpperCase().replace(/[ -]/g, '_');
  if (normalized === 'RESOLVED' || normalized === 'COMPLETED') return 'RESOLVED';
  if (normalized === 'IN_PROGRESS') return 'IN_PROGRESS';
  if (normalized === 'SCHEDULED') return 'SCHEDULED';
  if (normalized === 'AUTO_GENERATED') return 'AUTO_GENERATED';
  return 'ASSIGNED';
};

const toSeverity = (priority: string): WorkOrderSeverity => {
  const normalized = priority.toUpperCase();
  if (normalized === 'CRITICAL' || normalized === 'HIGH' || normalized === 'MEDIUM') return normalized;
  return 'LOW';
};

export const mapLiveWorkOrder = (dto: LiveWorkOrderDto, assets: Asset[]): WorkOrder => ({
  id: dto.id,
  assetId: dto.asset,
  assetName: assets.find((asset) => asset.id === dto.asset)?.name ?? dto.asset,
  severity: toSeverity(dto.priority),
  status: toWorkOrderStatus(dto.status),
  title: dto.title,
  assignedTechnician: dto.owner,
  autoGenerated: dto.source.toLowerCase().includes('ai')
});

export const mapLivePart = (dto: LivePartDto, suppliers: Supplier[]): InventoryPart => ({
  id: dto.id,
  name: dto.name,
  quantityOnHand: dto.onHand,
  reorderLevel: dto.reorderLevel,
  unitCost: dto.unitCost,
  supplierId: dto.supplierId,
  supplierName: suppliers.find((supplier) => supplier.id === dto.supplierId)?.name ?? dto.supplierId
});

export const mapLiveSupplier = (dto: LiveSupplierDto): Supplier => ({
  id: dto.id,
  name: dto.name,
  contact: dto.contact,
  contactPhone: dto.phone,
  rating: dto.rating
});

export const mapLiveAssets = (assets: LiveAssetDto[]) => assets.map(mapLiveAsset);
export const mapLiveSuppliers = (suppliers: LiveSupplierDto[]) => suppliers.map(mapLiveSupplier);
export const mapLiveParts = (parts: LivePartDto[], suppliers: Supplier[]) => parts.map((part) => mapLivePart(part, suppliers));
export const mapLiveWorkOrders = (orders: LiveWorkOrderDto[], assets: Asset[]) => orders.map((order) => mapLiveWorkOrder(order, assets));