import type { Asset, NotificationItem, WorkOrder } from '../types';

export function captureSimulationRecords<T extends object>(records: T): T {
  return structuredClone(records);
}

export function thresholdSeverity(value: number, baseline?: number, critical?: number) {
  if (
    !Number.isFinite(value) ||
    baseline === undefined ||
    critical === undefined ||
    !Number.isFinite(baseline) ||
    !Number.isFinite(critical) ||
    critical === baseline
  )
    return 'UNCONFIGURED';
  const ratio = (value - baseline) / (critical - baseline);
  return ratio >= 1 ? 'CRITICAL' : ratio >= 0.65 ? 'WARNING' : 'HEALTHY';
}

/** Evaluates a virtual fleet without APIs, timers, or mutations of the supplied LIVE copy. */
export function evaluateSimulationFleet(
  assets: Asset[],
  existingAlarms: Record<string, unknown>[],
  existingOrders: WorkOrder[],
  existingNotices: NotificationItem[],
  now = Date.now(),
) {
  const alarms = structuredClone(existingAlarms);
  const orders = structuredClone(existingOrders);
  const notices = structuredClone(existingNotices);
  const timestamp = new Date(now).toISOString();
  const fleet = structuredClone(assets).map((asset) => {
    let highest = 0;
    for (const sensor of asset.sensors) {
      const value = sensor.rawValue ?? sensor.currentValue;
      const severity = thresholdSeverity(value, sensor.baseline, sensor.criticalThreshold);
      if (severity === 'UNCONFIGURED') continue;
      const active = alarms.find(
        (a) => a.asset_id === asset.id && a.sensor_id === sensor.id && !a.resolved_at,
      );
      const notice = (title: string, message: string, workOrderId?: string) =>
        notices.unshift({
          id: crypto.randomUUID(),
          type: workOrderId ? 'WORK_ORDER' : 'ALERT',
          title,
          message,
          assetId: asset.id,
          workOrderId,
          timestamp,
          read: false,
        });
      if (severity === 'HEALTHY') {
        if (active) {
          active.resolved_at = timestamp;
          notice(
            `Alarm resolved: ${asset.name}`,
            `${sensor.name} returned below its warning threshold.`,
          );
        }
        continue;
      }
      highest = Math.max(highest, severity === 'CRITICAL' ? 2 : 1);
      const limit =
        severity === 'CRITICAL'
          ? sensor.criticalThreshold!
          : sensor.baseline! + (sensor.criticalThreshold! - sensor.baseline!) * 0.65;
      const message = `${sensor.name} = ${value} ${sensor.unit}; ${severity.toLowerCase()} limit ${Number(limit.toFixed(3))}.`;
      const incident = active ?? {
        id: crypto.randomUUID(),
        asset_id: asset.id,
        sensor_id: sensor.id,
        created_at: timestamp,
        resolved_at: null,
      };
      if (!active || active.severity !== severity)
        notice(`${severity} alarm: ${asset.name}`, message);
      Object.assign(incident, { severity, reading: value, threshold: limit, message });
      if (!active) alarms.unshift(incident);
      const incidentId = String(incident.id);
      const hasOrder = orders.some(
        (order) =>
          order.incidentId === incidentId ||
          (active &&
            order.status !== 'RESOLVED' &&
            order.autoGenerated &&
            !order.incidentId &&
            order.assetId === asset.id &&
            sensor.id in (order.triggerReadings ?? {})),
      );
      if (severity === 'CRITICAL' && !hasOrder) {
        const order: WorkOrder = {
          id: `WO-${crypto.randomUUID().slice(0, 12)}`,
          incidentId,
          assetId: asset.id,
          assetName: asset.name,
          severity: 'CRITICAL',
          status: 'AUTO_GENERATED',
          title: `Inspect ${sensor.name}`,
          description: message,
          assignedTechnician: 'Unassigned',
          triggerReadings: { [sensor.id]: value },
          aiRootCause:
            'Verify sensor and operating conditions; inspect equipment using approved isolation and maintenance procedures.',
          createdAt: timestamp,
          autoGenerated: true,
        };
        orders.unshift(order);
        notice('Automatic work order created', order.title, order.id);
      }
    }
    return {
      ...asset,
      status:
        highest === 2
          ? ('DOWN' as const)
          : highest === 1
            ? ('DEGRADED' as const)
            : ('HEALTHY' as const),
      healthScore:
        highest === 2
          ? Math.min(asset.healthScore, 45)
          : highest === 1
            ? Math.min(85, Math.max(70, asset.healthScore))
            : Math.max(90, asset.healthScore),
      telemetrySource: 'SIMULATION',
      connectionState: 'CONNECTED' as const,
      lastSeenAt: timestamp,
    };
  });
  return { assets: fleet, alarms, workOrders: orders, notifications: notices };
}

export function failureReading(asset: Asset | undefined, sensorType: string) {
  const sensor = asset?.sensors.find(
    (s) =>
      s.type.toLowerCase() === sensorType.toLowerCase() &&
      s.baseline !== undefined &&
      s.criticalThreshold !== undefined &&
      s.baseline !== s.criticalThreshold,
  );
  if (!asset || !sensor)
    throw new Error('This machine has no configured sensor for the selected failure test.');
  const direction = Math.sign(sensor.criticalThreshold! - sensor.baseline!);
  const margin = Math.max(Math.abs(sensor.criticalThreshold! - sensor.baseline!) * 0.2, 0.01);
  return {
    assetId: asset.id,
    sensorId: sensor.id,
    value: Number((sensor.criticalThreshold! + direction * margin).toFixed(3)),
    description: `Test ${sensor.name} beyond its critical threshold`,
  };
}
