import React, { useEffect, useRef, useState } from 'react';
import { Brain, Send, FileText, Upload, Trash2 } from 'lucide-react';
import { useSimulation } from '../../context/SimulationContext';
import { liveApi, type AiResult, type MaintenanceDocument } from '../../services/liveApi';
import { canPerform } from '../../services/accessControl';
type Action = 'chat' | 'analyze' | 'forecast' | 'draft-work-order' | 'diagnose';
const actions: {value:Action;label:string}[]=[{value:'chat',label:'Ask assistant'},{value:'analyze',label:'Analyze asset'},{value:'forecast',label:'Failure / repair forecast'},{value:'draft-work-order',label:'Draft work order'},{value:'diagnose',label:'Search maintenance manuals'}];
export const AiDiagnosticView: React.FC = () => {
 const { assets, mode, simulationSessionId, userRole, runAi, runAiDiagnosticQuery, createWorkOrder } = useSimulation();
 const [assetId,setAssetId]=useState(assets[0]?.id ?? '');
 const [question,setQuestion]=useState(''); const [action,setAction]=useState<Action>('chat');
 const [result,setResult]=useState<AiResult|null>(null);
 const [pending,setPending]=useState(false); const [error,setError]=useState(''); const [saved,setSaved]=useState(false);
 const [documents,setDocuments]=useState<MaintenanceDocument[]>([]); const [documentError,setDocumentError]=useState(''); const [uploading,setUploading]=useState(false);
 const fileInput=useRef<HTMLInputElement>(null); const scope=useRef(''); scope.current=`${mode}:${simulationSessionId}`;
 const loadDocuments=async()=>{const current=scope.current;try{const response=await liveApi.listDocuments(mode,simulationSessionId);if(scope.current===current){setDocuments(response.documents);setDocumentError('');}}catch(e){if(scope.current===current)setDocumentError(e instanceof Error?e.message:'Document library unavailable.');}};
 useEffect(()=>{setPending(false);setUploading(false);setResult(null);setError('');setSaved(false);setDocuments([]);setQuestion('');setAssetId(assets[0]?.id??'');void loadDocuments();},[mode,simulationSessionId]);
 const request=async()=>{
  if(pending||!assetId||!question.trim())return;
  const current=scope.current;setPending(true);setError('');setResult(null);setSaved(false);
  try{const response=action==='diagnose'?await runAiDiagnosticQuery(assetId,question).then(r=>({answer:r.answer,sources:r.sourceLabels??[]})):await runAi(action,assetId,question);if(scope.current===current)setResult(response);}
  catch(e){if(scope.current===current)setError(e instanceof Error?e.message:'AI request failed');}finally{if(scope.current===current)setPending(false);}
 };
 const attach=async(file:File)=>{const current=scope.current;setUploading(true);setDocumentError('');try{await liveApi.uploadDocument(file,mode,simulationSessionId);if(scope.current===current)await loadDocuments();}catch(e){if(scope.current===current)setDocumentError(e instanceof Error?e.message:'Upload failed');}finally{if(scope.current===current)setUploading(false);if(fileInput.current)fileInput.current.value='';}};
 const remove=async(id:string)=>{setUploading(true);try{await liveApi.removeDocument(id,mode,simulationSessionId);await loadDocuments();}catch(e){setDocumentError(e instanceof Error?e.message:'Could not remove document');}finally{setUploading(false);}};
 const confirm=async()=>{if(!result?.title||!result.priority)return;setPending(true);setError('');try{await createWorkOrder({assetId,title:result.title,priority:result.priority,description:result.description,recommendedAction:result.recommendedAction});setSaved(true);}catch(e){setError(e instanceof Error?e.message:'Unable to save');}finally{setPending(false);}};
 return <div className="space-y-6">
  <div className="bg-white rounded-xl p-6 border border-slate-200"><div className="flex items-center gap-3"><Brain className="w-6 h-6 text-blue-700"/><h1 className="text-2xl text-slate-900">Maintenance Assistant</h1></div><p className="mt-2 text-sm text-slate-600">Ask a question, analyze a machine, or prepare a work order. Responses use current records and relevant maintenance documents.</p></div>
  <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_320px]">
   <div className="bg-white rounded-xl p-6 border border-slate-200 space-y-4">
    <div className="grid sm:grid-cols-2 gap-4"><label className="block text-sm font-semibold">Asset<select value={assetId} onChange={e=>{setAssetId(e.target.value);setResult(null);setSaved(false);}} className="block w-full mt-2 border border-slate-300 rounded-md p-2.5 font-normal">{assets.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label className="block text-sm font-semibold">Task<select value={action} onChange={e=>setAction(e.target.value as Action)} className="block w-full mt-2 border border-slate-300 rounded-md p-2.5 font-normal">{actions.map(a=><option key={a.value} value={a.value}>{a.label}</option>)}</select></label></div>
    <form onSubmit={e=>{e.preventDefault();void request();}} className="space-y-3"><label className="block text-sm font-semibold">Your prompt<textarea placeholder="Ask anything about maintenance, your machines, or the attached documents…" value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void request();}}} className="block w-full mt-2 border border-slate-300 rounded-md p-3 font-normal" rows={4}/></label><div className="flex items-center justify-between gap-3"><p className="text-xs text-slate-500">Enter to send · Shift+Enter for a new line</p><button type="submit" disabled={pending||!assetId||!question.trim()} className="inline-flex items-center gap-2 bg-blue-700 hover:bg-blue-800 text-white text-sm font-semibold rounded-md px-4 py-2.5 disabled:opacity-50"><Send className="h-4 w-4"/>{pending?'Working…':'Send'}</button></div></form>
    {pending&&<p role="status" className="text-sm text-blue-700">Preparing your response…</p>}{error&&<p role="alert" className="text-sm text-rose-700 bg-rose-50 p-3 rounded">{error}</p>}
    {result&&<div className="border border-slate-200 rounded-lg p-4 space-y-3 text-sm">
     {result.riskLevel&&<p className="font-semibold">Risk: {result.riskLevel}</p>}{result.answer&&<p className="whitespace-pre-wrap leading-relaxed">{result.answer}</p>}{result.explanation&&<p className="leading-relaxed">{result.explanation}</p>}{result.recommendedChecks?.map(check=><p key={check}>• {check}</p>)}
     {result.title&&<><p className="text-xs font-semibold text-amber-700">AI draft — review before saving</p><label className="block">Title<input value={result.title} onChange={e=>setResult({...result,title:e.target.value})} className="block border rounded p-2 w-full"/></label><label className="block">Description<textarea value={result.description??''} onChange={e=>setResult({...result,description:e.target.value})} className="block border rounded p-2 w-full" rows={4}/></label><label className="block">Priority<select value={result.priority} onChange={e=>setResult({...result,priority:e.target.value as AiResult['priority']})} className="block border rounded p-2">{['LOW','MEDIUM','HIGH','CRITICAL'].map(p=><option key={p}>{p}</option>)}</select></label><p>Suggested parts (verify compatibility): {result.suggestedParts?.join(', ')||'None specified'}</p><button disabled={pending||saved||!canPerform(userRole,'createWorkOrder')} onClick={()=>void confirm()} className="bg-blue-700 text-white rounded px-4 py-2 disabled:opacity-50">{saved?'Work order saved':'Confirm and save work order'}</button></>}
     <div className="text-xs text-slate-500 border-t pt-3"><p className="font-semibold">Sources</p>{result.sources.length?result.sources.map(source=><p className="mt-1" key={source}>{source}</p>):<p>Current maintenance records. No relevant document was retrieved.</p>}</div>
    </div>}
   </div>
   <aside className="bg-white border border-slate-200 rounded-xl p-5 space-y-4 self-start"><h2 className="text-base flex items-center gap-2"><FileText className="h-4 w-4 text-blue-700"/>Maintenance documents</h2><p className="text-xs leading-relaxed text-slate-600">{mode==='LIVE'?'Attached documents are saved to your shared maintenance library.':'Simulation attachments are temporary and reset when you leave simulation.'} Relevant extracts are sent to the configured AI provider when you ask a question.</p><input ref={fileInput} type="file" accept=".pdf,.docx,.txt,.md" aria-label="Attach maintenance document" onChange={e=>{if(e.target.files?.[0])void attach(e.target.files[0]);}} className="hidden"/><button onClick={()=>fileInput.current?.click()} disabled={uploading} className="inline-flex items-center justify-center gap-2 border border-slate-300 hover:bg-slate-50 rounded-md px-3 py-2 text-sm w-full disabled:opacity-50"><Upload className="h-4 w-4"/>{uploading?'Updating library…':'Attach document'}</button><p className="text-xs text-slate-500">PDF, DOCX, TXT, Markdown · up to 10 MB</p>{documentError&&<p role="alert" className="text-xs text-rose-700">{documentError}<button className="block underline mt-1" onClick={()=>void loadDocuments()}>Retry library</button></p>}{documents.map(doc=><div key={doc.id} className="border-t border-slate-100 pt-3 flex items-start justify-between gap-2"><div className="min-w-0"><p className="text-sm font-medium break-words">{doc.filename}</p><p className="text-xs text-slate-500 mt-1">{doc.chunks} indexed sections · {(doc.bytes/1024).toFixed(1)} KB</p></div><button disabled={uploading} onClick={()=>void remove(doc.id)} aria-label={`Remove ${doc.filename}`} className="text-slate-400 hover:text-rose-600 p-1"><Trash2 className="h-4 w-4"/></button></div>)}{!documents.length&&!documentError&&<p className="text-xs text-slate-500">No documents attached yet.</p>}</aside>
  </div>
 </div>;
};
