import assert from 'node:assert/strict';
import {captureSimulationRecords,evaluateSimulationFleet, failureReading, thresholdSeverity} from '../src/services/simulationWorkflow.ts';

const live=[{id:'machine',name:'LIVE CNC',assetType:'Mill',machineClass:'Demo CNC',location:'Bay',healthScore:95,status:'HEALTHY',telemetrySource:'GENERATED_DEMO',lastSeenAt:'2026-10-03T00:00:00Z',sensors:[{id:'actual-live-vibration-id',name:'Spindle vibration',type:'Vibration',currentValue:1.7,rawValue:1.7,baseline:1.5,criticalThreshold:6.5,unit:'mm/s',history:[1.6,1.7]},{id:'coolant-pressure',name:'Coolant pressure',type:'Pressure',currentValue:4.3,baseline:4.5,criticalThreshold:2.1,unit:'Bar',history:[4.3]}]}];
const baseline=structuredClone(live);
const records={assets:live,workOrders:[],parts:[{id:'part',quantityOnHand:7}],notifications:[{id:'note',read:false}],stockMovements:[{quantity_delta:-1}]};
const virtual=captureSimulationRecords(records);
assert.deepEqual(virtual,records);
virtual.parts[0].quantityOnHand=0;virtual.notifications[0].read=true;virtual.stockMovements.push({quantity_delta:-3});
assert.equal(records.parts[0].quantityOnHand,7);assert.equal(records.notifications[0].read,false);assert.equal(records.stockMovements.length,1);
const preset=failureReading(live[0],'vibration');
assert.equal(preset.sensorId,'actual-live-vibration-id');
assert.ok(preset.value>6.5);
const changed=structuredClone(live);changed[0].sensors[0].currentValue=preset.value;changed[0].sensors[0].rawValue=preset.value;
const fault=evaluateSimulationFleet(changed,[],[],[],1000);
assert.deepEqual(live,baseline,'LIVE must not change');
assert.equal(fault.assets[0].status,'DOWN');
assert.equal(fault.alarms.length,1);assert.equal(fault.workOrders.length,1);assert.equal(fault.notifications.length,2);
assert.equal(fault.workOrders[0].triggerReadings[preset.sensorId],preset.value);
assert.equal(fault.workOrders[0].incidentId,String(fault.alarms[0].id));
const legacy={...fault.workOrders[0],incidentId:undefined,status:'RESOLVED'};
assert.equal(evaluateSimulationFleet(changed,[],[legacy],[],1500).workOrders.length,2);
const closed=fault.workOrders.map(order=>({...order,status:'RESOLVED'}));
const held=evaluateSimulationFleet(changed,fault.alarms,closed,fault.notifications,2000);
assert.equal(held.workOrders.length,1,'Closing a ticket for an ongoing incident must not duplicate it');
assert.equal(held.workOrders[0].status,'RESOLVED');
const recovery=evaluateSimulationFleet(live,held.alarms,held.workOrders,held.notifications,3000);
assert.ok(recovery.alarms[0].resolved_at);assert.equal(recovery.assets[0].status,'HEALTHY');
const recurrence=evaluateSimulationFleet(changed,recovery.alarms,recovery.workOrders,recovery.notifications,4000);
assert.equal(recurrence.workOrders.length,2,'A new incident after recovery needs a new ticket');
const pressure=failureReading(live[0],'Pressure');assert.ok(pressure.value<2.1);
const both=structuredClone(changed);both[0].sensors[1].currentValue=pressure.value;both[0].sensors[1].rawValue=pressure.value;
assert.equal(evaluateSimulationFleet(both,[],[],[],5000).workOrders.length,2);
assert.equal(thresholdSeverity(4.5-(4.5-2.1)*.7,4.5,2.1),'WARNING');
assert.equal(thresholdSeverity(NaN,1,2),'UNCONFIGURED');
assert.throws(()=>failureReading(live[0],'Unknown'));
const warning=structuredClone(live);warning[0].sensors[0].currentValue=5;warning[0].sensors[0].rawValue=5;
const warned=evaluateSimulationFleet(warning,[],[],[],6000);assert.equal(warned.alarms.length,1);assert.equal(warned.workOrders.length,0);
console.log('Passed: LIVE-copy isolation, dynamic presets, immediate faults without a timer, warning/critical alarms, triggering readings, per-incident work orders, resolution preservation, recurrence, multiple faults, and falling thresholds.');
