export type AssetStatus = 'HEALTHY' | 'DEGRADED' | 'DOWN';

export interface SensorReading {
  id: string;
  name: string;
  type: string;
  currentValue: number;
  baseline?: number;
  criticalThreshold?: number;
  unit: string;
  rawValue?: number;
  lastSeenAt?: string;
  history: number[]; // last 30 data points
}

export interface Asset {
  id: string;
  name: string;
  assetType: string;
  location: string;
  installDate?: string;
  healthScore: number;
  status: AssetStatus;
  machineClass: string;
  sensors: SensorReading[];
  lastSeenAt?: string;
  telemetrySource?: string;
  connectionState?: 'CONNECTED' | 'DELAYED' | 'DISCONNECTED';
  runningHours?: number;
  lastMaintenance?: string;
  assignedEngineer?: string;
}

export type WorkOrderSeverity = 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW';
export type WorkOrderStatus = 'AUTO_GENERATED' | 'ASSIGNED' | 'SCHEDULED' | 'IN_PROGRESS' | 'RESOLVED';

export interface WorkOrder {
  id: string;
  assetId: string;
  assetName: string;
  severity: WorkOrderSeverity;
  status: WorkOrderStatus;
  title: string;
  description?: string;
  aiRootCause?: string;
  triggerReadings?: Record<string, number>;
  incidentId?: string;
  aiConfidence?: number;
  partRequired?: string;
  partId?: string;
  partReserved?: boolean;
  assignedTechnician?: string;
  createdAt?: string;
  resolvedAt?: string;
  autoGenerated: boolean;
}

export interface InventoryPart {
  id: string;
  sku?: string;
  name: string;
  category?: string;
  quantityOnHand: number;
  reorderLevel: number;
  unitCost?: number;
  supplierId: string;
  supplierName?: string;
  leadTimeDays?: number;
  compatibleAssets?: string[];
}

export interface Supplier {
  id: string;
  name: string;
  contact?: string;
  tier?: 'Tier 1 OEM' | 'OEM Partner' | 'Certified Distributor';
  rating: number; // 0 - 5.0
  onTimeDeliveryRate?: number; // 0 - 100%
  contactEmail?: string;
  contactPhone?: string;
  location?: string;
  catalogCount?: number;
  suppliedParts?: string[];
}

export interface RagDocumentChunk {
  chunkId: string;
  sourceDoc: string;
  assetId?: string;
  similarityScore: number;
  text: string;
  section: string;
}

export interface AiAuditLog {
  id: string;
  timestamp: string;
  assetId: string;
  assetName: string;
  modelVersion: string;
  inputSensorVector: Record<string, number>;
  failureProbability: number;
  recommendedAction: string;
  triggeredWorkOrderId?: string;
  executionTimeMs: number;
}

export interface NotificationItem {
  id: string;
  timestamp: string;
  type: 'ALERT' | 'WORK_ORDER' | 'INVENTORY' | 'HEALED';
  title: string;
  message: string;
  assetId?: string;
  workOrderId?: string;
  partId?: string;
  read: boolean;
}

export type UserRole = 'ADMIN' | 'RELIABILITY_ENGINEER' | 'TECHNICIAN' | 'EXECUTIVE_VIEWER' | 'VIEWER';
